import type { Metadata } from 'next';
import Link from 'next/link';
import type { ReactNode } from 'react';
import Button from '@/components/ui/Button';
import Reveal from '@/components/ui/Reveal';
import Breadcrumbs from '@/components/ui/Breadcrumbs';

export const metadata: Metadata = {
  title: 'Terms of Use — SolveHFX',
  description:
    'Terms of Use for SolveHFX, including acceptable use, disclaimers, and service limitations.',
  alternates: { canonical: 'https://www.solvehfx.ca/terms' },
  openGraph: {
    title: 'Terms of Use — SolveHFX',
    description:
      'Read the terms and conditions for using SolveHFX civic reporting tools.',
    url: 'https://www.solvehfx.ca/terms',
  },
};

const EFFECTIVE_DATE = 'August 10, 2026';

function Mail() {
  return (
    <a
      className="text-primary hover:underline underline-offset-4"
      href="mailto:support@solvehfx.ca"
    >
      support@solvehfx.ca
    </a>
  );
}

const SECTIONS: { title: string; body: ReactNode }[] = [
  {
    title: 'Acceptance and eligibility',
    body: (
      <>
        <p>
          These Terms of Use are a binding agreement between you and SolveHFX. By
          accessing the site or submitting a report, you agree to them. If you do
          not agree, do not use the service.
        </p>
        <p className="mt-3">
          You must be at least 13 years old to submit a report. If you are between
          13 and the age of majority in your province, you may use SolveHFX only
          with the involvement of a parent or guardian.
        </p>
      </>
    ),
  },
  {
    title: 'What SolveHFX is',
    body: (
      <p>
        SolveHFX is a free tool that helps residents describe a civic issue and
        send it by email to the public body responsible for it, and where
        applicable to their district councillor. SolveHFX is a messenger. It does
        not repair anything, does not operate any municipal system, and has no
        authority over how a public body handles what it receives.
      </p>
    ),
  },
  {
    title: 'Not affiliated with HRM or any government',
    body: (
      <p>
        SolveHFX is an independent project. It is not affiliated with, endorsed
        by, operated by, or acting on behalf of Halifax Regional Municipality,
        Halifax Transit, Nova Scotia Public Works, Halifax Water, Nova Scotia
        Power, or any other public body or utility. Names of public bodies are
        used only to describe where reports are sent. Official municipal channels,
        including 311, remain available and operate independently of SolveHFX.
      </p>
    ),
  },
  {
    title: 'Do not use SolveHFX for emergencies',
    body: (
      <>
        <p className="font-medium text-text-primary">
          SolveHFX is not an emergency service and is not monitored around the
          clock.
        </p>
        <p className="mt-3">
          If there is a risk to life, health, or property — including fire,
          flooding, a downed power line, a gas leak, a collision, a crime in
          progress, or any immediately dangerous road condition — call 911. For
          urgent municipal matters call 311. For electrical hazards contact Nova
          Scotia Power; for water or sewer emergencies contact Halifax Water.
        </p>
        <p className="mt-3">
          Reports submitted through SolveHFX are delivered by email and may not be
          read for hours or days, if at all. Never rely on SolveHFX to summon
          emergency assistance or to prevent harm.
        </p>
      </>
    ),
  },
  {
    title: 'AI-generated content',
    body: (
      <>
        <p>
          SolveHFX uses an automated AI service to analyse the photo you upload
          and produce a draft title, category, and description. That draft is a
          suggestion generated by software. It can be wrong, incomplete, or
          misleading, including about the nature or severity of an issue.
        </p>
        <p className="mt-3">
          You are shown the draft before anything is sent, and you can edit it.
          When you submit, you adopt the content as your own report and are
          responsible for it. SolveHFX makes no representation that AI-generated
          text is accurate, and we are not liable for the content of any draft you
          choose to submit.
        </p>
      </>
    ),
  },
  {
    title: 'Your responsibility for what you submit',
    body: (
      <ul className="space-y-2">
        <li>Submit only truthful, good-faith reports about genuine civic issues.</li>
        <li>
          You are responsible for the accuracy and legality of everything you
          submit, including after you edit an AI draft.
        </li>
        <li>
          You confirm you have the right to upload each image and that submitting
          it does not breach anyone&apos;s rights.
        </li>
        <li>
          Do not include information about identifiable individuals, licence
          plates, or private property interiors that you do not have permission to
          share.
        </li>
        <li>
          Do not include sensitive personal information about yourself or anyone
          else in report text or images.
        </li>
      </ul>
    ),
  },
  {
    title: 'Prohibited conduct',
    body: (
      <ul className="space-y-2">
        <li>No false, misleading, defamatory, harassing, or abusive reports.</li>
        <li>No hate speech, threats, or unlawful material.</li>
        <li>No impersonation of public officials, residents, or organizations.</li>
        <li>No spam, promotional content, or commercial solicitation.</li>
        <li>
          No automated bulk submission, scraping abuse, malware, or attempts to
          disrupt or compromise the platform or the public bodies we send to.
        </li>
        <li>No use of the service to burden or interfere with municipal operations.</li>
      </ul>
    ),
  },
  {
    title: 'Content licence and public use',
    body: (
      <>
        <p>
          You keep ownership of everything you submit. By submitting a report, you
          grant SolveHFX a non-exclusive, royalty-free, worldwide, transferable
          licence to display, reproduce, adapt, and share the report content — the
          photo, description, issue category, and general location — for purposes
          connected to the service. This includes displaying it on public SolveHFX
          pages such as the issue map, reports feed, and scorecards, sharing it on
          social media or with news media to raise awareness of civic issues, and
          including it in aggregated statistics or open data exports.
        </p>
        <p className="mt-3">
          Personal contact details are excluded from this licence. Your name, email
          address, and IP address are never published, shared with media, posted to
          social media, or included in any public export. They are used only to
          route your report and, if you provided an email, to send you status
          updates.
        </p>
        <p className="mt-3">
          This licence survives deletion of your report to the extent needed for
          copies already published or distributed. If you want a report removed
          from public display, contact <Mail /> and we will review the request.
        </p>
      </>
    ),
  },
  {
    title: 'No guarantee of delivery, response, or resolution',
    body: (
      <p>
        We cannot guarantee that a report will be delivered, received, opened,
        read, accepted, prioritized, or acted on by any public body or councillor,
        or that any issue will be resolved within any timeframe or at all. Email
        delivery can fail, be filtered, or be ignored for reasons entirely outside
        our control. Response and resolution figures shown on the site are
        estimates based on the limited information available to us and should not
        be relied on as an official record.
      </p>
    ),
  },
  {
    title: 'Third-party services',
    body: (
      <p>
        SolveHFX depends on third-party providers for hosting, data storage,
        mapping, AI analysis, and email delivery. Those providers operate under
        their own terms, and outages, errors, or changes on their side can affect
        the service. We are not responsible for the acts or omissions of third
        parties. Links to external sites are provided for convenience and are not
        an endorsement.
      </p>
    ),
  },
  {
    title: 'Moderation, suspension, and termination',
    body: (
      <p>
        We may review, edit, limit, reject, remove, or suspend any content or
        access at our discretion and without notice, to protect residents, public
        bodies, and platform integrity. We may stop providing the service to
        anyone at any time. You may stop using SolveHFX at any time.
      </p>
    ),
  },
  {
    title: 'Feedback',
    body: (
      <p>
        If you send us suggestions, bug reports, or ideas, you grant us an
        unrestricted, royalty-free right to use them without obligation or
        compensation to you. Please do not send us anything you consider
        confidential.
      </p>
    ),
  },
  {
    title: 'Availability and changes',
    body: (
      <p>
        SolveHFX is provided free of charge and may be modified, interrupted,
        suspended, or discontinued at any time without notice. We may also change
        these Terms by publishing a revised version on this page with a new
        effective date. Continuing to use the service after a change means you
        accept the revised Terms.
      </p>
    ),
  },
  {
    title: 'No professional advice',
    body: (
      <p>
        Nothing on SolveHFX is legal, engineering, safety, or other professional
        advice. Information about jurisdiction, responsibility for a road or
        asset, timelines, or how to escalate an issue is general information only
        and may be incorrect or out of date.
      </p>
    ),
  },
  {
    title: 'Disclaimer of warranties',
    body: (
      <p>
        SolveHFX is provided on an as-is and as-available basis. To the fullest
        extent permitted by law, we disclaim all warranties, express, implied, or
        statutory, including merchantability, fitness for a particular purpose,
        non-infringement, accuracy, and uninterrupted or error-free operation. You
        use the service at your own risk.
      </p>
    ),
  },
  {
    title: 'Limitation of liability',
    body: (
      <>
        <p>
          To the fullest extent permitted by law, SolveHFX and its operator are not
          liable for any indirect, incidental, special, consequential, exemplary,
          or punitive damages, or for lost data, profits, revenue, reputation, or
          goodwill, arising from or related to your use of the service.
        </p>
        <p className="mt-3">
          This includes, without limitation, any loss or harm arising from a report
          that was not delivered, not acted on, delayed, inaccurate, or generated
          in whole or in part by AI, and from any condition or hazard that remained
          unrepaired.
        </p>
        <p className="mt-3">
          Because SolveHFX is provided free of charge, our total aggregate
          liability for all claims relating to the service is limited to CAD $100.
        </p>
      </>
    ),
  },
  {
    title: 'Your consumer rights',
    body: (
      <p>
        Some jurisdictions, including Nova Scotia, do not allow the exclusion of
        certain warranties or the limitation of certain liabilities. Nothing in
        these Terms limits rights you have under applicable consumer protection
        law that cannot lawfully be limited, and nothing here excludes liability
        for fraud, or for death or personal injury caused by negligence, where
        such exclusion is prohibited. Where a limitation is unenforceable, it
        applies to the maximum extent permitted.
      </p>
    ),
  },
  {
    title: 'Indemnification',
    body: (
      <p>
        You agree to defend, indemnify, and hold harmless SolveHFX and its
        operator from claims, damages, liabilities, losses, and expenses,
        including reasonable legal fees, arising from your use of the service,
        content you submit, your breach of these Terms, or your violation of any
        law or third-party right.
      </p>
    ),
  },
  {
    title: 'Time limit for claims',
    body: (
      <p>
        Any claim relating to the service must be brought within one year after
        the event giving rise to it, to the extent such a limitation is permitted
        by applicable law.
      </p>
    ),
  },
  {
    title: 'Resolving disputes',
    body: (
      <p>
        If you have a problem, contact <Mail /> first. Most issues can be resolved
        quickly and informally, and we ask that you give us a genuine opportunity
        to do so before starting formal proceedings.
      </p>
    ),
  },
  {
    title: 'Governing law',
    body: (
      <p>
        These Terms are governed by the laws of the Province of Nova Scotia and
        the applicable federal laws of Canada, without regard to conflict-of-law
        principles. The courts of Nova Scotia have jurisdiction, subject to any
        non-waivable right you have to bring proceedings where you live.
      </p>
    ),
  },
  {
    title: 'General',
    body: (
      <ul className="space-y-2">
        <li>
          <span className="text-text-primary">Entire agreement.</span> These Terms
          and the{' '}
          <Link className="text-primary hover:underline underline-offset-4" href="/privacy">
            Privacy Policy
          </Link>{' '}
          are the whole agreement between us about the service.
        </li>
        <li>
          <span className="text-text-primary">Severability.</span> If a provision is
          unenforceable, the rest remains in full force.
        </li>
        <li>
          <span className="text-text-primary">No waiver.</span> Not enforcing a
          provision is not a waiver of it.
        </li>
        <li>
          <span className="text-text-primary">Assignment.</span> You may not assign
          these Terms. We may assign them in connection with a transfer of the
          project.
        </li>
        <li>
          <span className="text-text-primary">Force majeure.</span> We are not liable
          for delays or failures caused by events beyond our reasonable control.
        </li>
        <li>
          <span className="text-text-primary">Survival.</span> Sections on content
          licence, disclaimers, limitation of liability, indemnification, and
          governing law survive termination.
        </li>
      </ul>
    ),
  },
  {
    title: 'Contact',
    body: (
      <p>
        Questions about these Terms can be sent to <Mail />.
      </p>
    ),
  },
];

export default function TermsPage() {
  return (
    <div>
      <section className="border-b border-rule bg-bg-elev">
        <div className="mx-auto max-w-3xl px-4 sm:px-6 pt-10 sm:pt-14 pb-10">
          <Breadcrumbs
            items={[{ label: 'Home', href: '/' }, { label: 'Terms of Use' }]}
          />
          <Reveal className="mt-5">
            <p className="text-[11.5px] font-semibold tracking-[0.16em] uppercase text-primary/70">
              Legal
            </p>
            <h1 className="mt-3 text-[clamp(2rem,5vw,3.5rem)] leading-[1.05] tracking-tight text-balance">
              Terms of Use
            </h1>
            <p className="mt-4 text-[15px] text-text-secondary">
              Effective date: {EFFECTIVE_DATE}
            </p>
          </Reveal>
        </div>
      </section>

      <section className="py-12 sm:py-16 px-4 sm:px-6">
        <article className="mx-auto max-w-3xl space-y-8 text-[15px] leading-[1.75] text-text-secondary">
          <Reveal>
            <p>
              These Terms of Use govern your use of SolveHFX. By using the service,
              you agree to them. Please read the sections on emergencies,
              AI-generated content, and limitation of liability carefully — they
              affect what you can rely on this service for.
            </p>
          </Reveal>

          {SECTIONS.map((section, i) => (
            <Reveal key={section.title} delay={Math.min(40 + i * 30, 400)}>
              <div>
                <h2 className="text-[20px] text-text-primary tracking-tight mb-2">
                  {i + 1}. {section.title}
                </h2>
                {section.body}
              </div>
            </Reveal>
          ))}

          <Reveal delay={420}>
            <div className="text-center pt-2">
              <Link href="/privacy">
                <Button variant="outline">View Privacy Policy</Button>
              </Link>
            </div>
          </Reveal>
        </article>
      </section>
    </div>
  );
}
